// Shared types for antenna simulation - will be generated by WF-ARCH
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AntennaParams {
    pub frequency: f64,
    pub elements: Vec<Element>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Element {
    pub position: [f64; 3],
    pub length: f64,
    pub radius: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SimulationResult {
    pub impedance: (f64, f64),
    pub gain_db: f64,
    pub pattern: Vec<Vec<f64>>,
}
